name: media_streamer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  bonsoir: ^6.0.2
  flutter:
    sdk: flutter
  intl: ^0.20.2
  media_kit: ^1.2.6
  media_kit_libs_android_video: ^1.3.8
  media_kit_video: ^2.0.1
  network_info_plus: ^7.0.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  provider: ^6.1.5+1
  shelf: ^1.4.2
  shelf_static: ^1.1.3
  sqflite: ^2.4.2
  youtube_explode_dart: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
